-- =============================================================================
-- HTF REFERENCE TABLES — Threat Classification, Subclassification, Roles, TTP
-- =============================================================================
-- Run AFTER 05_reference_tables.sql
-- Target: PostgreSQL 14+
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS htf;
COMMENT ON SCHEMA htf IS 'Hybrid Threat Finance reference data: classifications, roles, TTPs.';


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. THREAT CLASSIFICATION
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE htf.threat_classification (
    threat_class_id     SERIAL PRIMARY KEY,
    code                VARCHAR(10) NOT NULL UNIQUE,
    name                VARCHAR(255) NOT NULL,
    description         TEXT,
    example             TEXT,
    priority            INTEGER,
    notes               TEXT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tc_name ON htf.threat_classification (name);
COMMENT ON TABLE htf.threat_classification IS 'HTF threat classification categories (Drug Trafficking, Human Trafficking, etc.).';

CREATE TRIGGER trg_audit_threat_classification
    AFTER INSERT OR UPDATE OR DELETE ON htf.threat_classification
    FOR EACH ROW EXECUTE FUNCTION audit.fn_log_change('threat_class_id');


-- Seed data
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('01', 'Drug Trafficking', 'Narcotics sales via streets, darknet markets, or brokered shipments.', 'Synthetic opioid sales on darknet markets.', 1, 'Starting here with overall case gathering');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('02', 'Human Trafficking', 'Implies Exploitation for forced labor, sex, or services', 'Regular low-value transactions from regions known for trafficking.', 2, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('06', 'Fraud and Scams', 'Includes romance scams, BEC, investment fraud, synthetic identity fraud generating large-scale cash flows.', 'Romance scam victim sending money abroad repeatedly.', 3, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('07', 'Weapons', 'Black market sales of firearms or military-grade arms laundered through shells or smuggling.', 'Arms trafficked to conflict areas via shell corporations.', 4, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('09', 'Natural Resource Exploitation', 'Conflict minerals like diamonds or gold via forced labor laundered through trade.', 'Conflict diamonds trafficked from war zones.', 5, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('03', 'Terrorism Finance', '', '', 6, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('04', 'Sanctions Evasion', '', '', 7, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('05', 'Nation State Finance', 'Official revenues laundered by regimes for personal use or hybrid conflict financing.', 'State oil revenues diverted through offshore accounts.', 8, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('08', 'Counterfeit Goods', 'Fake luxury items, pharmaceuticals, or electronics often linked to cross-border hubs.', 'Fake luxury handbags imported from China.', 9, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('12', 'Corruption and Misappropriation', 'Public funds embezzlement or aid diversion laundered through assets.', 'Politician buying luxury properties with embezzled funds.', 10, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('11', 'Wildlife Trafficking', 'Illegal trade in wildlife, plants, and animal-derived products.', 'Illegal ivory trade smuggled across borders.', 11, '');
INSERT INTO htf.threat_classification (code, name, description, example, priority, notes) VALUES ('10', 'Antiquities and Art', '', '', 12, '');


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. THREAT SUBCLASSIFICATION
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE htf.threat_subclassification (
    threat_subclass_id      SERIAL PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    threat_classification   VARCHAR(255) NOT NULL,
    description             TEXT,
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    created_ts              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_ts              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tsc_name ON htf.threat_subclassification (name);
CREATE INDEX idx_tsc_class ON htf.threat_subclassification (threat_classification);
COMMENT ON TABLE htf.threat_subclassification IS 'HTF threat subclassification (e.g., Cocaine under Drug Trafficking).';

CREATE TRIGGER trg_audit_threat_subclassification
    AFTER INSERT OR UPDATE OR DELETE ON htf.threat_subclassification
    FOR EACH ROW EXECUTE FUNCTION audit.fn_log_change('threat_subclass_id');


-- Seed data
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Corruption (Misappropriation)', 'Corruption (Misappropriation)', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Counterfeit Goods', 'Counterfeit Goods', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Electronics', 'Counterfeit Goods', 'Manufacture and sale of fake consumer electronics (e.g., phones, chargers, batteries) that often lack safety standards, pose fire/electrocution risks, and infringe on trademarks.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Luxury Items', 'Counterfeit Goods', 'Counterfeiting of branded high-end goods like handbags, watches, clothing, and accessories to exploit brand value and deceive consumers, often funding organized crime.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Pharmaceuticals', 'Counterfeit Goods', 'Production and distribution of fake or substandard medications, including antibiotics, painkillers, or vaccines, leading to serious health risks and undermining public trust in healthcare.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Toys and Baby Products', 'Counterfeit Goods', 'Sale of non-certified, low-quality replicas of children''s products—such as dolls, teething toys, or strollers—often containing toxic materials or choking hazards due to lack of safety regulation.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Automotive Parts', 'Counterfeit Goods', 'Counterfeit car parts (e.g., brake pads, airbags, oil filters) sold as genuine, often fail under stress and contribute to accidents or vehicle failures.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Cosmetics and Personal Care Products', 'Counterfeit Goods', 'Imitation beauty products (e.g., makeup, lotions, shampoos) made with unregulated ingredients, sometimes containing harmful chemicals like lead or bacteria.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Food Products', 'Counterfeit Goods', 'Counterfeit or adulterated food items (e.g., fake olive oil, diluted honey, expired infant formula) misrepresented to consumers, risking illness and public health violations.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Footwear and Apparel', 'Counterfeit Goods', 'Knockoff shoes, sportswear, or branded clothing sold under false labels, often using poor-quality materials and produced in exploitative labor conditions.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Software and Digital Goods', 'Counterfeit Goods', 'Distribution of pirated software, operating systems, or counterfeit licensing keys, leading to security vulnerabilities, malware risks, and IP theft.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Drug Trafficking', 'Drug Trafficking', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Amphetamines', 'Drug Trafficking', 'Trafficking of stimulant drugs (e.g., methamphetamine) that are illegally manufactured and distributed for recreational or performance-enhancing use.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Cocaine', 'Drug Trafficking', 'Smuggling and distribution of cocaine, typically from South America to global markets, involving complex cartels and high violence.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Cannabis', 'Drug Trafficking', '');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Chemical Smuggling', 'Drug Trafficking', 'Illicit transport of precursor chemicals used in the production of drugs such as meth, ecstasy, or fentanyl, often across borders to avoid regulation.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Fentanyl', 'Drug Trafficking', 'Trafficking of a highly potent synthetic opioid, often mixed with other drugs and responsible for widespread overdose deaths; commonly produced in clandestine labs.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Heroin', 'Drug Trafficking', 'Movement and sale of this opioid derived from poppy plants, often linked to Southeast Asia, Southwest Asia, or Latin America; associated with physical dependence and overdose risks.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Ketamine', 'Drug Trafficking', 'Illicit distribution of this dissociative anesthetic, often stolen from medical supplies or imported illegally for recreational use or as a club drug.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('MDMA (Ecstasy or Molly)', 'Drug Trafficking', 'Production and trafficking of this synthetic drug, popular in nightlife and festival settings, often involving international networks and lab-based manufacturing.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Prescription Opioids (Oxycodone, Fentanyl)', 'Drug Trafficking', 'Diversion and illegal sale of pharmaceutical-grade opioids, often through pill mills, theft, or forgery; fuels addiction and overdose crises.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Synthetic Cannabinoids (Spice, K2)', 'Drug Trafficking', 'Trafficking of lab-made chemicals sprayed on plant material to mimic marijuana effects, frequently marketed as legal alternatives but often toxic and unpredictable.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Fraud and Scams', 'Fraud and Scams', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Elder Financial Abuse', 'Fraud and Scams', 'Misuse or theft of an elderly person''s assets by someone in a position of trust—such as a caregiver, relative, or fiduciary—often involving coercion, undue influence, or deception.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Elderly Scams', 'Fraud and Scams', 'Targeted fraud schemes (e.g., lottery scams, fake tech support, “grandparent” scams) that prey on older adults’ perceived vulnerabilities or limited digital literacy.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Hacking', 'Fraud and Scams', 'Unauthorized digital intrusion into accounts or devices, often used to siphon funds, change credentials, or steal sensitive data from elderly individuals.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('ID Theft', 'Fraud and Scams', 'Use of stolen personal information (e.g., Social Security numbers, Medicare IDs) to open fraudulent accounts, file false claims, or commit benefits fraud.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Investment Scams', 'Fraud and Scams', 'Fraudulent pitches for non-existent or high-risk investments—such as Ponzi schemes, fake bonds, or “can’t-miss” retirement deals—often aimed at retirees with savings.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Romance Scams', 'Fraud and Scams', 'Emotional manipulation of victims through online dating or social platforms to build false relationships, ultimately to solicit money under pretenses like emergencies or travel.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Crowdfunding Abuse', 'Fraud and Scams', 'Creation of fake charitable or medical fundraisers on platforms like GoFundMe, often using stolen photos or fabricated stories to exploit donors—especially sympathetic seniors.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Gift Card Fraud', 'Fraud and Scams', '');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Human Trafficking', 'Human Trafficking', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Arranged Marriage', 'Human Trafficking', 'Coercive or fraudulent marriage arrangements used to exploit victims for labor, sex, immigration fraud, or control.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Asian Massage/ Beauty Salon', 'Human Trafficking', 'Front businesses used to traffic individuals, often women, for sexual services under the guise of legitimate massage or beauty services.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Child Exploitation', 'Human Trafficking', 'The abuse or trafficking of minors for sexual acts, forced labor, pornography, or illegal adoption.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Cyber-Trafficking', 'Human Trafficking', 'Online recruitment, grooming, and exploitation of victims, often involving live-streamed abuse, digital coercion, or trafficking via dark web platforms.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Domestic Servitude', 'Human Trafficking', 'Victims, often migrants or minors, are forced to work in private homes under threat, control, and inhumane conditions.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Export Smuggling', 'Human Trafficking', 'Trafficking of individuals across borders for sale or exploitation in foreign countries, often under false promises of work or safety.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Forced Begging', 'Human Trafficking', 'Victims, including children and disabled individuals, are coerced or abducted to beg in public places, with proceeds taken by traffickers.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Forced Labor', 'Human Trafficking', 'Victims are made to work under threat or coercion, often in agriculture, construction, factories, or domestic work, without proper compensation.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('High-End Escort', 'Human Trafficking', 'Traffickers exploit individuals in luxury sex work markets, often under manipulation, threats, or debt bondage.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Import Smuggling', 'Human Trafficking', 'Victims are trafficked into a country, often hidden within illegal immigration networks, then forced into labor or sexual exploitation.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Online Dating', 'Human Trafficking', 'Traffickers pose as romantic interests to lure victims into abusive situations, forced sex work, or labor under false pretenses.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Organ Trafficking', 'Human Trafficking', 'Victims are coerced, deceived, or abducted to harvest organs for illegal sale, often with fatal or lifelong consequences.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Prostitution Management', 'Human Trafficking', 'Organized control of trafficked individuals in commercial sex operations, often involving quotas, movement restrictions, and threats.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Refugee/Migrant Exploitation', 'Human Trafficking', 'Vulnerable migrants and refugees are targeted for forced labor or sex trafficking due to lack of legal protections or resources.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Transnational Sales', 'Human Trafficking', 'Cross-border sale or trade of individuals, especially women and children, for exploitative purposes such as forced marriage, sex work, or labor.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Illicit Mineral/Gemstone Mining', 'Illicit Mineral/Gemstone Mining', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Coltan Smuggling', 'Illicit Mineral/Gemstone Mining', 'Illicit mining and cross-border trafficking of coltan, often involving armed groups, child labor, and environmental harm.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Conflict Diamonds', 'Illicit Mineral/Gemstone Mining', 'Diamonds mined in war zones and sold to fund armed conflict, linked to forced labor and human rights abuses.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Gold Trafficking', 'Illicit Mineral/Gemstone Mining', 'Illegal mining and trade of gold to fund crime or launder money, often involving smuggling, document fraud, and labor exploitation.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Rare Earth Mineral Smuggling', 'Illicit Mineral/Gemstone Mining', 'Illegal extraction and export of rare earth elements (e.g., lithium, cobalt) used in tech and green energy, often tied to corruption, labor abuse, and sanctions evasion.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Jade and Gemstone Laundering', 'Illicit Mineral/Gemstone Mining', 'Use of valuable stones like jade or rubies to launder money through inflated valuations or opaque cross-border trades. Common in Southeast Asia.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Mulitple', 'Multiple', 'Used for threat signals that span more than one threat classification and typology');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Nation State Finance', 'Nation State Finance', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('State-Sponsored Money Laundering', 'Nation State Finance', 'Laundering of illicit proceeds (e.g., corruption, arms sales) through state-owned banks, shell firms, or diplomatic channels.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Illicit Sovereign Wealth Use', 'Nation State Finance', 'Misuse or diversion of state funds (e.g., from sovereign wealth funds) for unauthorized political, personal, or military purposes.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Corruption & Embezzlement', 'Nation State Finance', 'Theft or diversion of public funds by government officials for personal or political gain.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('State-Sponsored Cybercrime', 'Nation State Finance', 'Government-backed theft of financial assets or data via hacking, ransomware, or crypto heists to fund operations or destabilize adversaries.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Unlawful Resource Exploitation', 'Nation State Finance', 'Profiting from illegal trade in oil, gas, minerals, or timber from occupied or contested regions.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Illicit Arms Financing', 'Nation State Finance', 'Use of covert funding mechanisms to purchase, produce, or distribute weapons in violation of international laws.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Foreign Influence via Donations or Bribes', 'Nation State Finance', 'Covert funding of political parties, lobbying efforts, or NGOs in foreign countries to manipulate policy or gain access.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Terrorism Finance', 'Terrorism Finance', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Nationalistic', 'Terrorism Finance', '');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Religious', 'Terrorism Finance', '');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Environmental', 'Terrorism Finance', '');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Political', 'Terrorism Finance', '');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Weapons', 'Weapons', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Military Systems Diversion', 'Weapons', 'Unauthorized sale or theft of advanced weapons like missiles, drones, or defense tech.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('NBCR Weapons Trafficking', 'Weapons', 'Illicit trade or development of nuclear, biological, chemical, or radiological weapons.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Small Arms Proliferation', 'Weapons', 'Illegal spread of firearms and light weapons, often fueling violence and instability.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Illicit Ammunition Trade', 'Weapons', 'Smuggling or black-market sale of bullets, explosives, or military-grade munitions.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Unlicensed Manufacturing', 'Weapons', 'Production of weapons or components without regulatory approval or oversight.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Arms Embargo Violations', 'Weapons', 'Sale or transfer of weapons to countries or groups under international sanctions.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Wildlife Trafficking', 'Wildlife Trafficking', 'Generic');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Ivory & Horn Trafficking', 'Wildlife Trafficking', 'Illegal trade of elephant ivory and rhino horns for luxury goods or traditional medicine, driving poaching and species decline.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Exotic Pets Trade', 'Wildlife Trafficking', 'Capture and smuggling of live animals—such as birds, reptiles, primates, and amphibians—for illegal sale in pet markets, often with high mortality rates.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Big Cat & Wildlife Parts', 'Wildlife Trafficking', 'Trafficking of body parts from tigers, lions, leopards, and other protected species for use in trophies, jewelry, fashion, and traditional medicine.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Marine Life Trafficking', 'Wildlife Trafficking', 'Illicit trade in sea turtles, corals, seahorses, and other marine species, typically for ornamental use, food, or traditional remedies.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Bushmeat & Traditional Medicine', 'Wildlife Trafficking', 'Hunting of wild animals for food or unregulated medicinal use (e.g., pangolin scales, bear bile), contributing to species endangerment and health risks.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Illegal Timber Trade', 'Wildlife Trafficking', 'Unauthorized logging and export of protected wood species, leading to deforestation, habitat loss, and often involving organized crime.');
INSERT INTO htf.threat_subclassification (name, threat_classification, description) VALUES ('Other', 'Other', '');


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. ROLES
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE htf.role (
    role_id             SERIAL PRIMARY KEY,
    code                VARCHAR(10),
    name                VARCHAR(255) NOT NULL,
    description         TEXT,
    context             VARCHAR(255),
    hierarchy           VARCHAR(100),
    ml_phase            VARCHAR(255),
    intent              VARCHAR(100),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_role_name ON htf.role (name);
CREATE INDEX idx_role_hierarchy ON htf.role (hierarchy);
COMMENT ON TABLE htf.role IS 'HTF financial crime roles (Facilitator, Financier, Money Mule, etc.).';

CREATE TRIGGER trg_audit_role
    AFTER INSERT OR UPDATE OR DELETE ON htf.role
    FOR EACH ROW EXECUTE FUNCTION audit.fn_log_change('role_id');


-- Seed data
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('1', 'Facilitator and support', 'A person outside the threat network who profits (or can be extorted/threatened) by supporting criminal or threat network operations by offering professional services, decision-making within an organizations (public/private), manipulating processes, or helping in any form.', 'Financial operator', 'Three levels', 'All three', 'Criminal/SUA');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('2', 'Financeer', 'A person within the organization who manages money laundering operations, logistics, funding, and procurement.', 'Financial operator', 'Operational/strategic', '', 'Criminal/SUA');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('3', 'Front owner/manager', 'A person who owns or controls a company, organization, etc. that serves as a point of collection of proceeds of crime and uses a financial account to comingle or place the proceeds.', 'Financial operator', 'Operations', '', 'Criminal/SUA');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('4', 'Retail sales proceed collector', 'A person who collects the proceeds of crime from contraband retailers.  This person must forward the proceeds to a wholesale distributer of contraband.', 'Financial operator', 'Tactical', 'Revenue generation', 'Criminal/SUA');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('5', 'Retiail wholesale distributor', 'A person who supplies contraband to retailers and receives payments for the goods and services.', 'Financial operator', 'Operations', 'Revenue generation', 'Criminal/SUA');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('6', 'Cash courier (money mule)', 'A person who transports cash through local or cross-border jurisdictions.  If a courier receives a payment for the service, he/she should be registered as an MSB, and if, the courier crosses an international border with more than the minimal required reporting amount, the crossing should be reported via a currency transaction report.  This person can be called a money mule.', 'Financial operator', 'Tactical', 'Layering', 'Criminal/SUA');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('7', 'Unwitting cash courier (money mule)', 'A person who unwittingly transports cash through local or cross-border jurisdictions.  If a courier receives a payment for the service, he/she should be registered as an MSB, and if the courier crosses a international border exceeding the required reporting amount, the person iobliged to notify authorities via a currency transaction report.', 'Victim', 'Tactical', 'Layering', 'Victim');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('8', 'Shell company owner', 'A person who registers a shell company as a legal commercial and financial structure needed to facilitate TN operations and/or money laundering.', 'Financial operator', 'Operations', '', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('9', 'Cashier (point-of-sale person)', 'A person who wittingly or unwittingly receives cash or payments without following policy or procedure in exchange for goods, services or financial instruments.', 'Financial operator', 'Tactical', 'Placement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('10', 'Funnel account holder', 'A person who controls a financial account that receives proceeds of crime or funds related to unlawful activity from two or more counterparties, who then moves funds to a different account.', 'Financial operator', 'Operations', 'Layering', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('11', 'Unlicensed money service business (MSB) operator', 'A person who operates and controlles an unlicesed money service business operator who facilitates the movement of funds or proceeds in violation of regulations. (includes HAWALA)', 'Financial operator', 'Operations', 'Layering', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('12', 'Money services busineeses (MSB) operator', 'A person who operates and controlles a licensed money services business that unwittingly or wittingly receives proceeds or crime or funds associated with unlawful activity. (includes HAWALA)', 'Financial operator', 'Operations', 'Placement and/or layering', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('13', 'Smurf', 'A person who belongs to a group of other smurfs that moves and places criminal proceeds or funds associated with unlawful activity under the direction and control of a leader,.  Usually smurfing is used as smurfing is used a a tactic to structure the placement of illicit funds.', 'Financial operator', 'Tactical', 'Placement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('14', 'Witting accountant', 'A  person who uses professional expertise to manipulate documents, receipts, falsifies revenue information, falsifies documents, and helps set up commercial activity with the purpose of obfuscating or camouflaging unlawful activity or the management of proceeds of crime.', 'Financial operator', 'Operations', 'All phases', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('15', 'Unwitting accountat', 'A person who serves as an accountant of another person, a group, or a company that is associated with unlawful activity without knowing about the connection.  (it includes a threatened or extorted accountant)', 'Victim', 'Operations', 'All phases', 'Victim');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('16', 'Purchaser', 'A person who pays for goods and/or services associated with logistics or operational support of unlawful activity.', 'Financial operator', 'Operations', 'All phases', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('17', 'Asset holding company controller', 'A person who controls an asset holding company that includes property, businesses (shells, brick and mortar), FI accounts in order to conceal, move out of the jurisdiction, and layer proceeds of crime or use funds to support unlawful or threatening activity.', 'Financial operator', 'Operations', 'All phases', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('18', 'Witting account holder', 'A person who has a FI account used for the placement and layering of funds, or as a conduit or funnel for the movmenent of proceeds of crime, or to use the account funds to make payments for goods or servcies that facilitate unalawful or threatening activities.', 'Financial operator', 'Operations', 'All phases', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('19', 'Straw purchaser', 'A person who is legally permitted to buy an item—such as a firearm, alcohol, or pharmaceuticals—purchases it on someone else''s behalf, typically to conceal their identity or because the true buyer is barred from purchasing. The straw buyer falsifies purchase forms, pretending to be the actual buyer to evade background checks or legal prerequisites. This practice weakens gun safety laws and promotes criminal activity.', 'Financial operator', 'Tactical', 'Placement, layering, integration', 'C/V');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('20', 'Beneficial owner', 'Is a natural person who ultimately owns or controls an entity, assets, or the individuals on whose behalf transactions are conducted.', 'Financial operator', 'Strategic', 'Integration', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('21', 'Structurer', 'A person or entity that deliberately subdivides large sums of illegal cash into smaller transactions to bypass reporting requirements set by financial institutions, aiming to conceal the funds'' illegal origin and enable their entry into the financial system. The goal is to evade detection by authorities and adhere to anti-money laundering (AML) laws, which require the reporting of sizeable cash transactions. The structurer may make these deposits individually or coordinate through one or more intermediaries known as ''smurfs''.', 'Financial operator', 'Tactical', 'Placement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('22', 'Non-Compliant Business', 'An entity, often a shell company or a business lacking strong anti-money laundering (AML) controls, is deliberately used by criminals to hide the source and movement of illicit funds. These businesses often ignore regulatory requirements, making them appealing targets for criminals who exploit their weak oversight for money laundering, such as structuring, trade-based money laundering, or blending illicit money with legitimate cash flows', 'Financial operator', 'Operational', 'All phases', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('23', 'Professional money launderer (PML)', 'A professional money launderer (PML) is an individual, organization, or network that deliberately offers money laundering services to criminals, criminal groups, or threat networks in return for payment. Unlike unaware participants, PMLs are fully conscious of their role in illegal or threatening activities and often leverage their specialized knowledge to develop intricate schemes that exploit legal loopholes and anti-money laundering (AML) protections.', 'Financial operator', 'Operational', 'All pahses', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('24', 'Unlicensed vendor', 'In a criminal context, an unlicensed vendor is an individual or entity that sells goods or services without the required permits or licenses. This often involves illegal activities such as tax evasion, the unauthorized sale of weapons and ammunition, pharmaceuticals, operating without proper health and safety certifications, or selling unregulated items. These violations can range from minor administrative offenses to serious crimes, depending on the jurisdiction and the type of goods involved, such as illegal firearms or uninspected food.', 'Financial operator', 'Operational', '', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('25', 'Drug trafficker', 'A person who spends large sums at every phase of their business—ranging from cultivation and manufacturing to distribution and sales—covering costs such as paying personnel, buying equipment, bribing officials, and laundering significant amounts of illegal cash. These expenses greatly fluctuate based on the scale and complexity of the operation.', 'Criminal expenditure & payments', 'Operational', 'Funding & procurement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('26', 'Raw material procuror (general)', 'A person who makes payments intending to acquire materials for cultivation, synthesis, or manufacturing of any illegal product, or supports the purchase of materials needed to fabricate weapons, electronic devices, or surveillance equipment associated with threatening activities.', 'Criminal expenditure & payments', 'Operational', 'Funding & procurement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('27', 'Drug fabrication raw material procuror', 'A person who makes a payment to obtain materials needed for the cultivation, manufacturing, synthesis, or illegal drugs. For synthetic drugs like fentanyl and methamphetamine, this includes buying precursor chemicals. For plant-based drugs, it involves costs for seeds, fertilizer, and irrigation. The purchases can include lab equipment, storage management tools, or any equipment necessary to produce illicit drugs.', 'Criminal expenditure & payments', 'Operational', 'Funding & procurement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('28', 'Purchaser and maitainance of packaging machinery', 'A person who, by trade, responsibility, or role within a TCO, is responsible for purchasing and maintaining equipment used for processing and packaging illegal drugs or any type of contraband.', 'Criminal expenditure & payments', 'Operational', 'Funding & procurement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('29', 'Drug manufacture labor payor', 'A person who pays for labor in drug manufacturing.', 'Criminal expenditure & payments', 'Operational', 'Funding & procurement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('30', 'Drug related official corruption payor', 'A person involved in smuggling or criminal operations who pays bribes to government officials, police, border agents, or any inspector overseeing, controlling, and preventing processes related to illegal activities to ensure that the official facilitates the illicit drug trade or at least turns a blind eye. The payment of bribes enables the smooth flow of contraband, money, or other illicit activities that are typically regulated by authorities.', 'Criminal expenditure & payments', 'Tactical', 'Funding & procurement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('31', 'Bribe receipient', 'A person who can be a government official, police officer, border agent, or any inspector responsible for overseeing, controlling, and preventing illegal activities, who accepts a bribe to support, advance, or facilitate a contraband or smuggling operation.', 'Criminal expenditure & payments', 'Tactical', 'Operational facilitation', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('32', 'Money mule recruiter', 'A person who recruits individuals to launder illegal drug money, thereby disconnecting the criminal group from the flow of illicit cash. This recruiter serves as a vital link in the money laundering process, which involves using multiple bank accounts and transferring funds to disguise their source and complicate the money trail.', 'Criminal expenditure & payments', 'Tactical', 'Placement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('33', 'Drug retailer', 'A person who is a street-level or person-to-person drug dealer, selling and distributing illegal drugs to end-users. The retailer is the final link in the drug supply chain.', 'Criminal expenditure & payments', 'Tactical', 'Placement', 'Criminal');
INSERT INTO htf.role (code, name, description, context, hierarchy, ml_phase, intent) VALUES ('34', 'Drug addict customer', 'A person who has an addiction and who is supplied by a retailer with illicit drugs.', 'Victim', 'Tactical', 'Revenue generation', 'Victim');


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. TTP (Tactics, Techniques, and Procedures)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE htf.ttp (
    ttp_id              SERIAL PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    definition          TEXT,
    complexity_level    VARCHAR(50),
    hierarchy           VARCHAR(100),
    stage               VARCHAR(100),
    scheme              VARCHAR(255),
    tactical_category   VARCHAR(255),
    fi_detectible       VARCHAR(10),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ttp_name ON htf.ttp (name);
CREATE INDEX idx_ttp_scheme ON htf.ttp (scheme);
CREATE INDEX idx_ttp_complexity ON htf.ttp (complexity_level);
COMMENT ON TABLE htf.ttp IS 'HTF Tactics, Techniques, and Procedures for financial crime.';

CREATE TRIGGER trg_audit_ttp
    AFTER INSERT OR UPDATE OR DELETE ON htf.ttp
    FOR EACH ROW EXECUTE FUNCTION audit.fn_log_change('ttp_id');


-- Seed data
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('STRUCTURING', 'Splitting large sums of money into smaller transactions to avoid triggering reporting thresholds.', 'Medium', 'Tactical', 'Placement', '1 - Ꝏ', 'Placement and reporting avoidance.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CASH INTENSIVE BUSINESS', 'Blending (comingling) illicit funds with legitimate earnings in businesses that inherently deal with a lot of cash makes it harder to distinguish between legal and illegal income.', 'Medium', 'Operational', 'Placement', 'BUSINESS STRUCTURES', 'Placement and reporting avoidance.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('FRONT COMPANY', 'A front company, also known as a front organization or front corporation, is a legitimate-looking business employed to conceal the illegal proceeds of a crime.', 'Medium', 'Operational', 'Placement', 'BUSINESS STRUCTURES', 'Placement and transfers.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('TRADE BASED MONEY LAUNDERING (TBML)', 'Trade-Based Money Laundering (TBML) scheme involves criminals or threat networks exploiting international trade to hide the illegal origins of their funds and integrate them into the legitimate financial system. Usually, this involves manipulating trade aspects such as prices, quantities, and documentation to transfer value across borders while concealing the true nature of the transactions.', 'Complex', 'Operational', 'Layering', 'INTERNATIONAL COMMERCE', 'International movement of funds and facilitation of contraband.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('FUNNEL ACCOUNT', 'A funnel account is a financial account used in money laundering to collect illegal funds through small, structured deposits in one area, then quickly move the money elsewhere by withdrawal or transfer. This method hides the source of the funds and makes tracing difficult.', 'Medium', 'Operational', 'Layering', '1 - Ꝏ', 'Aggregation of proceeds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('UNDER INVOICING', 'Under-invoicing is a method employed in trade-based money laundering (TBML) whereby the price of goods or services indicated on an invoice is deliberately stated below their true market value. The discrepancy between the under-invoiced price and the genuine market value represents an added amount conveyed from the exporter to the importer, frequently utilized for settling outstanding obligations or transferring illicit funds.', 'Medium', 'Operational', 'Layering', 'SUPPLY CHAIN', 'Mis-invoicieng, quantity and document manipulation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('OVER INVOICING', 'Over-invoicing is a practice frequently employed in trade-based money laundering (TBML), a complex mechanism designed to conceal illegal funds within legitimate international trade transactions.', 'Medium', 'Operational', 'Layering', 'SUPPLY CHAIN', 'Mis-invoicieng, quantity and document manipulation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('MULTIPLE INVOICING', 'Criminals issue multiple invoices for the same international trade transaction (goods or services) to repeatedly transfer funds under the pretense of several trade transactions and commodity flows that exist only on paper.', 'Medium', 'Operational', 'Layering', 'SUPPLY CHAIN', 'Mis-invoicieng, quantity and document manipulation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BULK CASH SMUGGLING', 'Bulk cash smuggling involves illegally moving large amounts of money across borders to avoid detection by law enforcement and evade reporting rules.', 'Simple', 'Tactical', 'Placement', 'CASH SMUGGLING', 'Movement  of funds.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CAROUSEL TRANSACTIONS', 'Repeatedly importing and exporting the same valuable commodity to justify numerous payments and conceal the origin of funds.', 'Complex', 'Operational', 'Layering', 'SUPPLY CHAIN', 'Misrepresentation of goods ans services.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BLACK MARKET PESO EXCHANGE (BMPE)', 'This scheme sees criminals using illegal proceeds, such as drug trafficking funds, to purchase goods from exporters on behalf of importers in countries with currency restrictions. The importers then sell these goods locally and pay the criminals in the local currency, effectively converting illicit funds into legitimate currency without directly involving the formal banking system.', 'Complex', 'Operational', 'Layering', 'TBML', 'Value transfer.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('THIRD PARTY INTERMEDIARIES', 'Using third-party intermediaries like shell companies or offshore entities to handle invoice payments and mask the money trail even more.', 'Medium', 'Operational', '', 'SUPPLY CHAIN', 'Supply chain and intermediary exploitation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('SHELL COMPANY', 'Shell companies are purely paper entities. Criminals, threat networks, and money launderers often use these entities to disguise the origins of illicit funds by conducting a series of transactions. For instance, a shell company might claim to ''purchase'' services from another shell owned by the same criminal group or transfer money as "payments" for fake goods or services. Such structures significantly hinder authorities'' efforts to trace the true source of funds. Many criminals choose to register shell companies in countries with weak regulations and strict privacy laws to better hide their activities.', 'Complex', 'Operational', '', 'BUSINESS STRUCTURES', 'Legal fronts.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('SHELF COMPANY', 'A shelf company (also called a shelf corporation) is like a ready-made corporate entity stored on a shelf, waiting for someone to take over. It is a business that has been registered but lacks real operations or transactions. Essentially, a shell company exists to provide a long enough history of corporate records to avoid triggering compliance red flags, unlike newly registered companies.', 'Medium', 'Operational', '', 'BUSINESS STRUCTURES', 'Misinformation and deception about longevity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PHANTOM (GHOST) SHIPPING', 'Ghost shipping is a key technique in trade-based money laundering (TBML), where criminals simulate legitimate trade transactions to conceal the illicit source of funds.', 'Medium', 'Operational', '', 'SUPPLY CHAIN', 'Mis-invoicing, quantity, and document manipulation.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('INFILTRATION INTO LEGITIMATE SUPPLY CHAINS', 'Criminals and threat networks can penetrate legitimate supply chains by engaging unknown third parties in transactions to purchase goods, thereby incorporating illicit cash into the financial settlement process.', 'Medium', 'Operational', '', 'SUPPLY CHAIN', 'Supply chain and intermediary exploitation.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('FALSELY DESCRIBED GOODS AND SERVICES', 'Criminals and threat networks can produce false invoices, documents, packing lists, and certificates of origin to justify moving funds through the global supply chain and paying for logistics services and goods. This tactic is linked to TBML operations.', 'Complex', 'Operational', '', 'SUPPLY CHAIN', 'Misrepresentation of goods ans services.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('MISUSE OF EXISTING TRADE CHAINS', 'Using established trade routes and structures to transfer funds for illicit activities such as terrorist financing or evading sanctions.', 'Medium', 'Operational', '', 'SUPPLY CHAIN', 'Supply chain and intermediary exploitation.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('SUCCESSIVE ON-SELLING AT HIGHER VALUE', 'Buying and selling properties quickly can indicate money laundering. Criminals or threat networks use this strategy to hide transactions and complicate audits, making it hard to track illegal activities. They buy a property and then sell it at a higher price to a related third party, such as a trust or company, creating the illusion of a legitimate profit without giving up ownership. Repeatedly changing ownership and recording profits this way can legitimize large sums of money, making it harder to trace them to their illegal sources.', 'Complex', 'Operational', '', 'REAL ESTATE', 'Successive movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('UNDER VALUATION OF PROPERTY', 'Undervaluing occurs when a buyer offers significantly less than the property''s market value, at least officially. This means the sale contract records a lower price than what is actually paid. The buyer (often involved in illegal activities) secretly compensates the seller for the difference using illicit funds. If the property is then resold at market value or above, the profit from this sale is deposited into the bank as legitimate income.', 'Complex', 'Operational', '', 'REAL ESTATE', 'Property price manipulation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('OVER VALUATION OF PROPERTY', 'Overvaluing happens when a criminal buys a property at a price much higher than the market value, to secure the largest possible loan or mortgage from a lender. The bigger the loan or mortgage, the more illegal funds can be laundered while paying off the debt.', 'Complex', 'Operational', '', 'REAL ESTATE', 'Property price manipulation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BUYER COLLUSION', 'This technique, used by criminals or threat networks to launder large amounts of illicit funds and make property transactions appear legitimate, involves collusion among multiple buyers. These buyers conspire to bid against each other, thereby gaining an unfair market advantage. This strategy gives them the best chance of winning the highest bid for the illegally obtained funds to be transferred.', 'Complex', 'Operational', '', 'REAL ESTATE', 'Buyer collusion.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('MONEY LAUNDERING THROUGH LOANS', 'Launderers use loans or mortgages to disguise and incorporate illicit funds into valuable assets such as real estate. They typically take out loans or mortgages to launder illegal profits. For instance, criminals may purchase property using legitimate funds for the deposit and then secure a mortgage for the remaining amount, thereby mimicking a standard purchase. Mortgage payments are made with money derived from criminal activities, merging illegal and legitimate funds. Since these payments usually stay below the $10,000 reporting threshold, criminals can secretly transfer money through lenders. When they sell the property, the proceeds appear legitimate and are less likely to be traced to criminal sources.', 'Complex', 'Operational', '', 'REAL ESTATE', 'Loan laundering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('THIRD PARTY PURCHASE', 'Criminals or threat networks use a third party to buy property. This can be done by using a third party’s bank account to deposit and withdraw illegal funds for property purchases or, alternatively, by employing a third party—such as a friend or family member—to conduct transactions on their behalf. In some cases, third parties may be unwitting individuals with no criminal record. This complex arrangement distances the criminals from the illegal funds, keeps their information off the title and other documents, conceals ownership, and ultimately lowers the risk of authorities detecting the purchase for investigation. After the purchase, the money launderer may either pay the mortgage by funneling money through the lender or resell the property quickly to recover the investment.', 'Complex', 'Operational', '', 'REAL ESTATE', 'Use of third parties.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CONVERTING CASH INTO CHIPS', 'Criminals or threat networks can introduce illicit cash by buying casino chips, blending illegal funds with legitimate ones.', 'Simple', 'Operational', '', 'CASINO', 'Casino placement', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('DEPOSIT OF FUND INTO CASINO ACCOUNTS', 'Criminals or threat networks deposit proceeds of crime directly into casino accounts.', 'Simple', 'Operational', '', 'CASINO', 'Casino placement', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('STRUCTURING TRANSACTIONS (SMURFING)', 'To circumvent reporting thresholds like the $10,000 limit for Currency Transaction Reports (CTRs) in the US, criminals often split large sums of money into smaller amounts. They deposit these gradually or at various locations, sometimes employing multiple individuals.', 'Simple', 'Tactical', '', 'CASINO', 'Reporting avoidance', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('MINIMAL PLAY', 'A money launderer acquires chips, makes several low-risk bets to simulate genuine gambling activity, and then cashes out the chips as "winnings." This process allows the illicit funds to be mistaken for legitimate gambling earnings.', 'Simple', 'Operational', '', 'CASINO', 'Casino placement', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('ANONYMOUS OWNERSHIP', 'Shell companies hide owners'' identities using nominee directors or registration in jurisdictions with loose disclosure rules, making it hard for law enforcement to track illicit funds back to those involved.', 'Medium', 'Operational', '', 'SHELL COMPANY', 'Beneficial ownership & anonymity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('COMPLEX OPERATIONA & MINIMAL OPERTIONS', 'Shell companies typically lack a physical presence, workforce, or active business operations, and are principally utilized for financial transactions. These entities are frequently established within intricate ownership frameworks spanning multiple jurisdictions, which complicates the identification of the ultimate beneficial owner (UBO). The structuring of such arrangements, known as layering, is commonly associated with activities such as money laundering.', 'Medium', 'Operational', '', 'SHELL COMPANY', 'Beneficial ownership & anonymity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('FAKE INVOICING & SERVICES', 'Criminals use shell companies to issue fake invoices for nonexistent goods or services, making illicit funds appear legitimate and concealing their origins within the legal economy.', 'Medium', 'Operational', '', 'SHELL COMPANY', 'Mis-invoicieng, quantity and document manipulation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('ASSET PURCHASES', 'Shell companies may be utilized to acquire assets such as real estate or luxury items, with illicit funds potentially being used for these transactions. Subsequently, ownership may be transferred repeatedly through various shell entities, significantly complicating efforts to trace the financial flows and identify the actual owner of the assets.', 'Medium', 'Operational', '', 'SHELL COMPANY', 'Storage of value and decreasing tracebility.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('OFFSHORE COMPANY & ACCOUNTS', 'Shell companies are frequently set up in offshore financial centers with strict banking secrecy, low taxes, and little ownership transparency. These locations appeal to those wishing to conceal assets and activities.', 'Medium', 'Operational', '', 'SHELL COMPANY', 'Tax heaven and transparency obfuscation.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CASH PURCHASE OF CRYPTOCURRENCY', 'Criminals and threat networks might use crypto ATMs or P2P platforms to exchange illegal cash for cryptocurrency, making it harder to trace the original source.', 'Simple', 'Tactical', '', 'DIGITAL ASSETS', 'Placement into digital assets (cryptocurrency).', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('TRANSFER INTO CRYPTO WALLET', 'Criminals or threat networks can transfer digitalized proceeds into a cryptocurrency wallet to store value or serve as a conduit for further transferring value.', 'Simple', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset value storage.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CHAIN HOPPING', 'Converting one cryptocurrency into another across different blockchains or platforms makes it harder to trace transactions.', 'Simple', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset layering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF PRIVACY COINS', 'Cryptocurrencies such as Monero and Zcash are built to provide greater privacy, making transactions more difficult to trace.', 'Simple', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset layering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF MULTIPLE WALLETS', 'Criminals and threat networks create a complex web of transactions to confuse investigators and complicate tracing.', 'Medium', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset layering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF DECENTRALIZED (DeFi) PROTOCOLS', 'DeFi platforms, lacking minimal regulatory oversight, enable criminals and threat networks to exploit services like lending and swapping, which can be used for money laundering.', 'Medium', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset layering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('DECNTRALIZED EXCHANGES (DEX)', 'DEXs allow direct cryptocurrency trading, avoiding traditional financial institutions and their AML checks, which can facilitate money laundering.', 'Medium', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset layering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PAYING FOR GOODS & SERVICES', 'Criminals and threat networks use digital assets (cryptocurrency) to integrate proceeds of crime by paying for goods and services.', 'Medium', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset integration.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CONVERTING DIGITAL ASSETS INOT FIAT CURRENCY', 'Criminals and threat networks use digital asset exchanges that usually have weak AML programs to convert the value into fiat currency.', 'Medium', 'Tactical', '', 'DIGITAL ASSETS', 'Digital asset integration.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('EARLY POLICY SURRENDER', 'Criminals buy insurance policies, especially life insurance, with illegal money and then cancel them early, often taking a loss, to get seemingly legitimate payouts.', 'Medium', 'Operational', '', 'INSURANCE EXPLOITATION', 'Early policy termination.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('POLICY OVERPAYMENT', 'Crime proceeds are used to pay premiums above their actual cost, with the excess then claimed back as a refund, effectively "cleaning" the money.', 'Medium', 'Operational', '', 'INSURANCE EXPLOITATION', 'Proceeds laundering', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('EXAGERATED CLAIMS', 'Criminals submit fraudulent or exaggerated claims to the insurer to obtain payouts that are laundered money.', 'Medium', 'Operational', '', 'INSURANCE EXPLOITATION', 'Proceeds laundering', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('POLICY LOANS', 'Criminals use high cash value life insurance policies as collateral for loans, effectively transforming illegal money into seemingly legitimate loan proceeds.', 'Medium', 'Operational', '', 'INSURANCE EXPLOITATION', 'Proceeds laundering', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('UNUSUAL POLICY PURCHASE PAYMENTS', 'Criminals often use cash, money orders, or other hard-to-trace methods for large premium payments.', 'Medium', 'Operational', '', 'INSURANCE EXPLOITATION', 'Proceeds laundering', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('THIRD PARTY PAYMENTS', 'Payments are made by or directed to third parties, which makes it hard to trace the source of funds.', 'Complex', 'Operational', '', 'INSURANCE EXPLOITATION', 'Beneficial ownership & anonymity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('STRUCTURING MULIPLE POLICIES', 'Criminals buy many small policies, keeping payments under reporting thresholds to avoid detection.', 'Complex', 'Operational', '', 'INSURANCE EXPLOITATION', 'Placment strucuring', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('OWNERSHIP CHANGE', 'Beneficial ownership of insurance policies is transferred, and the new owner withdraws funds or takes loans against the policy, obscuring the original source of funds.', 'Complex', 'Operational', '', 'INSURANCE EXPLOITATION', 'Beneficial ownership & anonymity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('LACK OF TRADITIONAL CDD/KYC RECORSS', 'Many hawala operate outside the formal and regulated banking and financial industry sector, making it difficult to trace transactions due to the lack of compliance with AML industry standards.', 'Medium', 'Operational', '', 'HAWALA', 'Placement and movement of funds.', 'JURISDICTION DEPENDANT');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CROSS BORDER PAYMENTS', 'Hawala facilitates cross-border payments without requiring the physical movement of funds. Hawaladar settles IOUs using any form of payment and at any time of settlement.', 'Simple', 'Operational', '', 'HAWALA', 'Placement and movement of funds.', 'PROBABLE');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('RAPID TRANSFERS AFTER CASH DEPOSITS', 'Frequent deposits followed by immediate withdrawals can be a sign of layering.', 'Simple', 'Operational', '', '1 - Ꝏ / FI', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('TRANSACTIONS BETWEEN MULTIPLE ACCOUNTS AT THE SAME INSTITUTION', 'Funds are often transferred repeatedly between multiple accounts as a tactic to layer the funds.', 'Simple', 'Operational', '', '1 - Ꝏ / FI', 'Layering funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF FINTECH', 'Criminals and threat networks utilize Fintech services because of their speed of transactions, cross-border capabilities, and movement into less-regulated jurisdictions.', 'Simple', 'Operational', '', 'FINTECH', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CORRESPONDING BANKING', 'Local banks offer services to foreign banks via correspondent banking relationships. These relationships can be used to transfer funds to foreign bank accounts or banks in different regions within a large country, hiding their source.', 'Complex', 'Operational', '', '1- Ꝏ', 'Interjurisdictional layering', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PURCHASE OF PRECIOUS METALS & GEMS', 'Payments for precious metals and gems offer a tangible asset that retains value. These assets are easy to transport or sell, enabling the conversion of illicit funds into seemingly legitimate proceeds.', 'Medium', 'Operational', '', 'HIGH VALUE ITEM', 'TBML and movement of value.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PREPAID CARD', 'Preloaded with funds, these cards aren’t directly linked to a bank account, making it easier for criminals to keep their transactions less traceable. They function like regular debit or credit cards but offer greater anonymity. Preloaded cards can also be used to pay for goods or services related to illegal or threatening activities.', 'Simple', 'Tactical', '', 'STORED VALUE', 'Low profile and portability and access to funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BEARER INSTRUMENT', 'Bearer instruments are financial instruments such as bonds or checks that are owned by the person who possesses them, rather than being registered to a specific individual. This anonymity and ease of transfer make them particularly vulnerable to money laundering activities, as they can be used to conceal the origin and ownership of illegal funds.', 'Simple', 'Operational', '', 'STORED VALUE', 'Low profile and portability and access to funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('MONEY MULE', 'Criminals or threat networks employ money mules—individuals who transfer funds via their accounts following criminal instructions or physically move illegally obtained money for others. A money mule can be complicit, a witting mule (looks the other way), or an unwitting one.', 'Simple', 'Tactical', '', '1- Ꝏ', 'Movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BANK CAPTURE', 'In countries with lax anti-money laundering regulations, criminals or money launderers can take control of a bank, enabling them to transfer illicit funds without oversight.', 'Complex', 'Strategic', '', '1- Ꝏ', 'Complex illicit finance management and money laundering.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('ROUND TRIPPING', 'Criminals and threat networks move money through a series of transactions involving different accounts, individuals, shell companies, and countries with weak regulations. After these outbound transfers happen, the money is returned to the owner (the originator of the move) with a look of legitimacy. The goal is to create a complicated route that is hard to trace.', 'Complex', 'Operational', '', 'BUSINESS STRUCTURES', 'Circular flow of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BLACK SALARIES', 'It is a money laundering technique that involves paying unregistered employees in cash using funds that are illegally obtained and untaxed.', 'Medium', 'Operational', '', 'BUSINESS STRUCTURES', 'Exploitation, fraud, tax evation.', 'NO');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('NOMINEE TRUSTIES', 'Criminals or threat networks designate a nominee trustee—either an individual or entity—to oversee the trust, keeping the true beneficiary hidden. This adds a layer of secrecy, complicating law enforcement''s efforts to identify the actual owner behind the trust.', 'Medium', 'Operational', '', 'TRUST FUNDS', 'Beneficial ownership & anonymity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('OFFSHORE TRUSTS', 'Criminals or threat networks build trusts in jurisdictions characterized by weak regulations and high financial secrecy, commonly known as tax havens. This makes it easier to hide beneficial ownership and flow of funds.', 'Medium', 'Operational', '', 'TRUST FUNDS', 'Beneficial ownership & anonymity.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('MISLEADING TRANSACTIONS', 'Funds can be moved between individuals, companies, not-for-profit organizations, and trusts using seemingly legitimate payment methods like rental agreements, service charges, or buy-and-selling contracts.', 'Medium', 'Operational', '', '1- Ꝏ', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF MONEY ORDERS', 'Criminals and threat networks can use money orders to place illicit funds, transfer funds, or pay for goods and services with minimal traceability due to their cash-like nature and ease of transfer.', 'Simple', '', '', 'MONEY SERVICES BUSINESSES', 'Placement, movement & payments.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('THIRD PARTY CHECK CASHING', 'Criminals or threat networks can exploit check-cashing services by establishing a method for cashing checks made out to individuals or entities not directly associated with the account holder, potentially indicating the involvement of money mules or shell companies.', 'Medium', 'Tactical', '', 'MONEY SERVICES BUSINESSES', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('GAMBLING INTEGRATION CHECK CASHING', 'Proceeds of crime are used to purchase chips, gamble, and then cash out winnings as "clean" money, creating a plausible explanation for the funds.', 'Simple', 'Tactical', '', '1- Ꝏ', 'Layering and integration.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF REMITTANCE SERVICES', 'Criminals or threat networks use remittance services to transfer and conceal funds derived from crime, often with reduced quality and quantity of KYC data.', 'Simple', 'Tactical', '', 'MONEY SERVICES BUSINESSES', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF MULTIPLE AGENTS', 'Criminals and threat networks utilize multiple remittance agents or companies, thereby complicating the money trail and making it harder to trace the funds back to their origin', 'Simple', 'Tactical', '', 'MONEY SERVICES BUSINESSES', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PHASED REMITTANCES', 'Criminals gradually transfer funds over time, disguising them as normal, smaller transactions like salary, family assistance (cross-border), or maintenance payments to avoid suspicion.', 'Simple', 'Tactical', '', 'MONEY SERVICES BUSINESSES', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('WEALTH MANAGEMENT', 'Criminals and threat networks use wealth management firms because of their focus on high-value transactions and complex structures, which often attract money launderers.', 'Medium', 'Strategic', '', 'WEALTH MANAGEMENT', 'Movement and storage of value & funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CERTIFICATE OF DEPOSIT', 'Proceeds of crime can be used to deposit certificates of deposit (CD).  Proceeds can be structured into several CD accounts.', 'Medium', 'Operational', '', 'BANKING', 'Placement and storage of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('DEMAND DEPOSIT ACCOUNTS DEPOSITS', 'Demand Deposit Accounts (DDAs), similar to checking accounts, are vulnerable to money laundering and funding illegal activities because of their ease of access and ability to facilitate various transactions.', 'Medium', 'Operational', '', 'BANKING', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('SAVINGS ACCOUNT DEPOSITS', 'Cash Deposits: Criminals often deposit large sums of cash into savings accounts, breaking them into smaller, seemingly harmless deposits to avoid reporting obligations like Currency Transaction Reports for transactions over $10,000 in the US. Structuring/Smurfing: This involves dividing big amounts of illegal money into smaller, less conspicuous sums and depositing them across various banks or accounts to escape detection. Physical Movement of Funds: Fraudulent cash is physically moved across borders and deposited into accounts in countries with weak anti-money laundering (AML) laws.', 'Simple', 'Operational', '', 'BANKING', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('DEPOSIT INTO PERSONAL CHECKING ACCOUNTS', 'Personal checking accounts can be exploited for money laundering, often helping to place illegal funds into the financial system or hide their origin. Additionally, these accounts can be used for layering or to make payments for goods and services needed to support unlawful or threatening activities.', 'Simple', 'Operational', '', 'BANKING', 'Placement and movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('DIGITAL WALLET', 'Criminals or threat networks launder money or make payments through digital wallets that utilize the speed, anonymity, and global reach of these platforms to hide the illegal origins of funds.', 'Simple', 'Tactical', '', 'MONEY SERVICES BUSINESSES', 'P2P movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF MULTIPLE DIGITAL WALLETS', 'Criminals or threat networks set up numerous mobile payment accounts and digital wallets, often using false identification, to hide the movement of money. They transfer funds between these accounts and wallets, forming a complex web of transactions that is hard to trace.', 'Medium', 'Operational', '', 'MONEY SERVICES BUSINESSES', 'P2P movement of funds.', 'YES');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('ILLEGAL GAMBLING OPERATION', 'Illegal gambling refers to betting activities that do not comply with national, federal, state, or local laws. The classification as illegal is based on the absence of required legal and regulatory authorization rather than the nature of the activity. Consequences for illegal gambling vary by jurisdiction and severity and may include misdemeanor or felony charges and possible imprisonment.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CASINO MONEY LAUNDERING', 'Threat networks utilize the cash-intensive nature and financial mechanisms of casinos to facilitate money laundering, converting illegal proceeds into ostensibly legitimate gambling winnings.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('ANTIQUES MARKET EXPLOITATION', '', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('SUBJECTIVE VALUATION OF ART', 'Threat actors exploit the subjective nature of art valuation, which is influenced by individual opinions, emotions, experiences, and prevailing market trends rather than objective measures of quality or cost. This approach enables them to legitimize fund transfers under the guise of art transactions. The inherent variability and absence of standardized appraisal methods result in significant price fluctuations, with the value of artwork ultimately determined by the amount a buyer is prepared to pay.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('COLLUSION BETWEEN PLAYERS', 'Groups of threat actors collaborate in games like poker, deliberately losing to a chosen "winner" who then cashes out the pooled money as legitimate winnings, laundering illicit funds.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('SUBJECTIVE VALUATION OF ANTIQUES', 'Threat actors exploit the highly subjective and variable nature of antique valuations. By manipulating prices—such as over-invoicing transactions to facilitate the transfer of illicit funds abroad or under-invoicing to avoid taxes and import duties—they exploit these characteristics for illegal financial activities.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PURCHASING AND SELLING ANTIQUES', '', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('FREEPORT AND WAREHOUSE ON-SITE SALES', 'Threat actors exploit freeports and on-site warehouses to conduct sales used for money laundering because their structures tend to be opaque, offer tax incentives, and are subject to less customs or regulatory oversight.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('ART & ANTIQUE SECURED LOANS', 'Threat actors use artwork or antiquities that may be overvalued, counterfeit, or stolen as collateral for legitimate loans. The funds obtained from these loans are subsequently laundered and integrated into the legitimate economy.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('BUYING ANOTHER PLAYER''S GAMBLING WINNINGS', 'Criminals buy off legitimate jackpot winners with cash, sometimes at a premium, in exchange for their official winning check from the casino. This provides the criminal with a clean, traceable financial instrument.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CASINO HIGH-ROLLER/VIP ACCOUNTS', 'Threat actors use high-roller or "front money" accounts to deposit large amounts of illegal funds, transfer money between international casinos (taking advantage of different jurisdictions'' laws), and then withdraw the funds with less scrutiny, often through wire transfers.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('PAYING OFF CASINO DEBTS', 'Criminal proceeds are used to cover the gambling debts of a high-loss player, after which the launderer receives legitimate funds from that individual as reimbursement.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('GAMBLING MIXING METHODS AND ASSETS', 'Threat actors engaging in illicit activities obscure the origins of criminal proceeds by employing intricate strategies that combine gambling with non-gambling techniques. For example, funds may be transferred via cryptocurrencies to online accounts and subsequently withdrawn into real estate or other legitimate assets.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('VANCOUVER GAMBLING MONEY LAUNDERING METHOD', '', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('CASINO JUNKET PROGRAMS EXPLOITATION', 'In the casino industry, a ''junket'' is a gambling trip arranged by a junket operator for high-net-worth players at a particular casino, coordinated with the casino operator under agreed terms. The structure of casino junket programs may be used to facilitate money laundering. In some instances, these arrangements have been utilized to transfer funds and provide credit, potentially obscuring the origin of assets, especially when services such as cashing out winnings or currency exchanges are provided, often involving offshore transactions.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF FUNNEL ACCOUNT', 'Threat actors engage in money laundering by using funnel accounts to leverage personal or business bank accounts and other financial institutions. This process typically involves making numerous, often small, cash deposits in one or more geographic regions, followed by rapid withdrawals or transfers of the consolidated funds to another location.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('GEOGRAPHIC DISPERSION OF DEPOSITS INTO A FUNNEL ACCOUNT', 'Threat actors oversee deposits into a funnel account and conduct transactions at multiple branches of a financial institution distributed across a broad geographic region (such as different states, provinces, or countries). This approach complicates the process of linking individual deposits to a single origin.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('FUNNEL ACCOUNT INTEGRATION', 'Threat actors or criminals can use aggregated funds in an account to directly pay for goods and services of the licit economy or to fund unlawful activities.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('IOLTA FUNNEL ACCOUNTS', 'Criminally controlled Interest on Lawyers'' Trust Accounts (IOLTA) is used to receive funds from sources that may be proceeds of crime. Due to their typical function of pooling nominal or short-term client funds for charitable purposes, these accounts often receive less rigorous bank oversight than standard accounts, making them vulnerable to exploitation by threat actors.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('TRUST AND COMPANY SERVICE PROVIDER (TCSP) EXPLOITATION', 'Threat actors use TCSPs to create hidden corporate structures that conceal illegal funds and true ownership. They set up shell companies or trusts, employ nominee directors, and exploit cross-border transactions to move money and avoid detection.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('TCSP USE OF NOMINEE DIRECTORS AND SHAREHOLDERS', 'TCSPs offer nominee services in which individuals are designated as directors or shareholders of a company without exercising actual control, thereby concealing the identities of the beneficial owners within the corporate structure.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('USE OF TCSP READY-TO-GO COMPANIES', 'Individuals seeking to obscure ownership may acquire pre-incorporated, "ready-to-go" entities from Trust and Company Service Providers (TCSPs). The actual proprietors can remain undisclosed for extended periods, enabling various financial transactions or potentially serving as channels to support or facilitate illicit activities, including money laundering.', '', '', '', '', '', '');
INSERT INTO htf.ttp (name, definition, complexity_level, hierarchy, stage, scheme, tactical_category, fi_detectible) VALUES ('EQUINE INVESTING IN BREEDING AND RACING OPERATIONS', 'Threat actors invest resources in horse farms, training facilities, and breeding programs. These operations allow threat actors to launder large amounts of money through expenses and investments, making it harder to track financial flows.', '', '', '', '', '', '');


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. TTP SIGNAL
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE htf.ttp_signal (
    ttp_signal_id           SERIAL PRIMARY KEY,
    ttp_signal_name         VARCHAR(50) NOT NULL,
    ttp_signal_description  VARCHAR(255) NOT NULL,
    ttp_signal_family       VARCHAR(50) NOT NULL,
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    created_ts              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_ts              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ttp_signal_name ON htf.ttp_signal (ttp_signal_name);
CREATE INDEX idx_ttp_signal_family ON htf.ttp_signal (ttp_signal_family);
COMMENT ON TABLE htf.ttp_signal IS 'TTP signal definitions grouped by signal family.';

CREATE TRIGGER trg_audit_ttp_signal
    AFTER INSERT OR UPDATE OR DELETE ON htf.ttp_signal
    FOR EACH ROW EXECUTE FUNCTION audit.fn_log_change('ttp_signal_id');


-- ─────────────────────────────────────────────────────────────────────────────
-- 6. TTP RECORD
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE htf.ttp_record (
    ttp_record_id       SERIAL PRIMARY KEY,
    role_id             INTEGER NOT NULL REFERENCES htf.role(role_id),
    threat_subclass_id  INTEGER NOT NULL REFERENCES htf.threat_subclassification(threat_subclass_id),
    ttp_id              INTEGER NOT NULL REFERENCES htf.ttp(ttp_id),
    ttp_signal_id       INTEGER REFERENCES htf.ttp_signal(ttp_signal_id),
    source_id           INTEGER REFERENCES provenance.source(source_id),
    description         TEXT NOT NULL,
    detection_logic     TEXT NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    user_id             VARCHAR(255) NOT NULL,
    created_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_ts          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ttp_rec_role ON htf.ttp_record (role_id);
CREATE INDEX idx_ttp_rec_subclass ON htf.ttp_record (threat_subclass_id);
CREATE INDEX idx_ttp_rec_ttp ON htf.ttp_record (ttp_id);
CREATE INDEX idx_ttp_rec_signal ON htf.ttp_record (ttp_signal_id);
COMMENT ON TABLE htf.ttp_record IS 'Links a specific role + threat subclass + TTP with detection logic. Core analytical artifact.';

CREATE TRIGGER trg_audit_ttp_record
    AFTER INSERT OR UPDATE OR DELETE ON htf.ttp_record
    FOR EACH ROW EXECUTE FUNCTION audit.fn_log_change('ttp_record_id');
